###
// Get bike passes for a Smart System bike
GET https://api.bosch-ebike.com/bike-pass/smart-system/v1/bike-passes?bikeId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Authorization: Bearer {{$auth.token("euda-test-confidential")}}
Content-Type: application/json
