###
// Get installation reports of a specified bike.
GET https://api.bosch-ebike.com/software-update/smart-system/v1/installation-reports?createdAfter=2020-01-01T00:00:00.000Z&createdBefore=2026-01-01T00:00:00.000Z&limit=5&offset=0&bikeId=550e8400-e29b-41d4-a716-446655440000
Authorization: Bearer {{$auth.token("euda-test-confidential")}}
Content-Type: application/json
