@bikeId=00000000-0000-0000-0000-000000000000

###
// Get installation reports of a bulk configuration change for a Smart System bike
GET https://api.bosch-ebike.com/bulk-configuration/smart-system/v1/installation-reports?bikeId={{bikeId}}
Authorization: Bearer {{$auth.token("euda-test-confidential")}}
Content-Type: application/json
