@partNumber = 12345678914
@serialNumber = 1707261/0447

###
// Get all available battery measurement field data collected by Bosch Capacity Tester (Smart System).
GET https://api.bosch-ebike.com/diagnosis-field-data/smart-system/v1/capacity-testers?partNumber={{partNumber}}&serialNumber={{serialNumber}}
Authorization: Bearer {{$auth.token("euda-test-confidential")}}
Content-Type: application/json
