@bikeId=00000000-0000-0000-0000-000000000000

###
// List all eBikes
GET https://api.bosch-ebike.com/bike-profile/smart-system/v1/bikes
Authorization: Bearer {{$auth.token("euda-test-confidential")}}
Content-Type: application/json

###
// Retrieve a single eBike
GET https://api.bosch-ebike.com/bike-profile/smart-system/v1/bikes/{{bikeId}}
Authorization: Bearer {{$auth.token("euda-test-confidential")}}
Content-Type: application/json