@partNumber = 12345678914
@serialNumber = 1707261/0447

###
// Get installation reports of a specified bike
GET https://api.bosch-ebike.com/diagnosis-field-data/ebike-system-2/v1/drive-units?partNumber={{partNumber}}&serialNumber={{serialNumber}}&createdAfter=2020-01-01T00:00:00.000Z&createdBefore=2020-01-01T00:00:00.000Z&limit=10&offset=0
Authorization: Bearer {{$auth.token("euda-test-confidential")}}
Content-Type: application/json
